# Generated by Django 5.2.9 on 2025-12-18 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investML', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Building',
            new_name='Tickers',
        ),
    ]
