# Generated by Django 5.2.9 on 2025-12-26 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investML', '0008_remove_portfolio_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='reaction_to_20_percent_drop',
        ),
    ]
