# Generated by Django 5.2.9 on 2025-12-27 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investML', '0012_remove_portfolio_budget_alter_portfolio_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='budget',
            field=models.FloatField(default=0),
        ),
    ]
