# syntax=docker/dockerfile:1
# Use an official Python runtime as a parent image
FROM python:3.12-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container


# Copy the rest of the application code into the container
COPY . .

# Define the command to run the application when the container starts
CMD ["python", "./retrain.py"]
