# Generated by Django 5.2.9 on 2025-12-21 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investML', '0002_rename_building_tickers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickers',
            old_name='name',
            new_name='ticker',
        ),
        migrations.RemoveField(
            model_name='tickers',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tickers',
            name='tickers',
        ),
        migrations.AddField(
            model_name='tickers',
            name='budget',
            field=models.FloatField(default=0),
        ),
    ]
