# Generated by Django 5.2.9 on 2025-12-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investML', '0007_tickers_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='name',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='risk_tolerance',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='total_budget',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='average_monthly_income',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='investing_experience_years',
            field=models.IntegerField(default=0, help_text='Years of investing experience (0–4)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='investment_percentage',
            field=models.FloatField(default=0, help_text='Percentage of savings to invest (0–100)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='reaction_to_20_percent_drop',
            field=models.FloatField(default=0, help_text='Amount you would invest more after 20% drop'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='salary_stability',
            field=models.IntegerField(choices=[(1, 'Very unstable'), (2, 'Unstable'), (3, 'Average'), (4, 'Stable'), (5, 'Very stable')], default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='portfolio',
            name='time_horizon_years',
            field=models.PositiveIntegerField(default=0, help_text='How many years until you need this money'),
            preserve_default=False,
        ),
    ]
