# Generated by Django 5.2.9 on 2025-12-27 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investML', '0010_portfolio_budget_portfolio_risk_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='risk_level',
        ),
    ]
