# Generated by Django 5.2.9 on 2025-12-27 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investML', '0013_portfolio_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='risk',
            field=models.FloatField(default=0.0),
        ),
    ]
