# Generated by Django 5.2.9 on 2026-03-11 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investML", "0015_alter_tickers_prediction"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sentiment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=100)),
                ("sentiment_text", models.TextField()),
                ("date", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
