# Generated by Django 5.2.9 on 2026-03-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investML", "0016_sentiment"),
    ]

    operations = [
        migrations.AddField(
            model_name="sentiment",
            name="label",
            field=models.IntegerField(default=0),
        ),
    ]
