# Generated by Django 5.2.9 on 2026-03-12 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("investML", "0017_sentiment_label"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sentiment",
            name="label",
        ),
    ]
