# Generated by Django 5.2.9 on 2026-05-25 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investML', '0019_risktoleranceprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RiskToleranceProfile',
        ),
    ]
