# Generated by Django 5.2.9 on 2026-05-25 01:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investML', '0020_delete_risktoleranceprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskToleranceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_horizon_years', models.PositiveIntegerField(help_text='In how many years do you plan to begin withdrawing major funds from this portfolio?', validators=[django.core.validators.MinValueValidator(1)])),
                ('emergency_fund_months', models.IntegerField(choices=[(0, '0 to 2 months'), (1, '3 to 6 months'), (2, '6+ months')], help_text='How many months of living expenses are covered by cash/liquid assets outside of this stock portfolio?')),
                ('portfolio_net_worth_ratio', models.IntegerField(choices=[(3, 'Less than 25%'), (2, '25% to 50%'), (1, 'More than 50%')], help_text='What percentage of your total liquid net worth does this investment represent?')),
                ('hypothetical_drawdown_reaction', models.IntegerField(choices=[(0, 'Panic: I would sell everything to cash immediately to prevent further loss.'), (1, 'Anxious: I would freeze, do nothing, but lose sleep over it.'), (2, 'Patient: I would hold tight, knowing the equity market moves in cycles.'), (3, 'Opportunistic: I would treat it as a discount sale and buy more shares.')], help_text='If your equity portfolio drops 25% in one month, what is your most likely reaction?')),
                ('past_behavior_2022', models.IntegerField(choices=[(0, "I didn't own stocks then / I panic-sold my positions."), (1, 'I held onto my stocks but felt highly uncomfortable.'), (2, 'I systematically held and rebalanced, or added capital.')], help_text='During the last major market correction (e.g., 2022 bear market), how did you handle your investments?')),
                ('tradeoff_preference', models.IntegerField(choices=[(1, 'Low volatility, predictable returns, minimal chance of massive single-year drops.'), (2, 'Average volatility, mimics the broader S&P 500 benchmark performance.'), (3, 'High volatility, chasing significant outperformance with the risk of multi-year downturns.')], help_text='Which investment profile makes you more comfortable?')),
                ('calculated_score', models.IntegerField(blank=True, editable=False, null=True)),
                ('assigned_profile', models.CharField(blank=True, choices=[('CONSERVATIVE', 'Conservative Equity (Low Volatility / Dividend Focus)'), ('MODERATE', 'Moderate Equity (Core Broad-Market / Balanced Sectors)'), ('AGGRESSIVE', 'Aggressive Equity (Growth Focus / High Beta)'), ('SPECULATIVE', 'Hyper-Aggressive / Speculative Equity (Concentrated / Small-Cap)')], editable=False, max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
