# Generated by Django 5.2.9 on 2026-05-29 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investML', '0021_risktoleranceprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RiskToleranceProfile',
        ),
    ]
