name: Monthly Job

on:
  schedule:
    - cron: '12 4 3 * *'  # 13:07 KST (UTC+9)
  workflow_dispatch:

jobs:
  monthly:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello
        run: echo "hello world"

        

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GSP_SA_KEY }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: investml-484904

      - name: Verify auth
        run: |
          gcloud auth list
          gcloud config list project